<?php

namespace xrpgBundle\Repository;

/**
 * actionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class actionsRepository extends \Doctrine\ORM\EntityRepository
{
}
