<?php

namespace xrpgBundle\Repository;

/**
 * acttipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class acttipoRepository extends \Doctrine\ORM\EntityRepository
{
}
