<?php

namespace xrpgBundle\Repository;

/**
 * AssetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssetsRepository extends \Doctrine\ORM\EntityRepository
{
}
