<?php

namespace xrpgBundle\Repository;

/**
 * bustoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bustoRepository extends \Doctrine\ORM\EntityRepository
{
}
