<?php

namespace xrpgBundle\Repository;

/**
 * campaignsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class campaignsRepository extends \Doctrine\ORM\EntityRepository
{
}
