<?php

namespace xrpgBundle\Repository;

use Symfony\Component\HttpFoundation\Response;
/**
 * CharactersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharactersRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCharactersData($parameters){
        $em = $this->getEntityManager();

        //$characters= $em->getRepository('xrpgBundle:characters')->findBy(array('nombre'=>$parameters['nombre']));
        $characters= $em->getRepository('xrpgBundle:characters')->findAll();

//        $dql = "select c.id,c.nombre from xrpgBundle:characters c where c.nombre='Dunia'";
//        $query = $em->createQuery($dql);
//        $characters = $query->getResult();

        return new  response(json_encode(array('characters'=>$characters)));
    }
}
