<?php

namespace xrpgBundle\Repository;

/**
 * currencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class currencyRepository extends \Doctrine\ORM\EntityRepository
{
}
