<?php

namespace xrpgBundle\Repository;

/**
 * estaturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class estaturaRepository extends \Doctrine\ORM\EntityRepository
{
}
