<?php

namespace xrpgBundle\Repository;

/**
 * lugaresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lugaresRepository extends \Doctrine\ORM\EntityRepository
{
}
