<?php

namespace xrpgBundle\Repository;

/**
 * mansRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mansRepository extends \Doctrine\ORM\EntityRepository
{
}
