<?php

namespace xrpgBundle\Repository;

/**
 * misionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class misionesRepository extends \Doctrine\ORM\EntityRepository
{
}
