<?php

namespace xrpgBundle\Repository;

/**
 * misproRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class misproRepository extends \Doctrine\ORM\EntityRepository
{
}
