<?php

namespace xrpgBundle\Repository;

/**
 * objectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class objectsRepository extends \Doctrine\ORM\EntityRepository
{
}
