<?php

namespace xrpgBundle\Repository;

/**
 * objefectosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class objefectosRepository extends \Doctrine\ORM\EntityRepository
{
}
