<?php

namespace xrpgBundle\Repository;

/**
 * ojosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ojosRepository extends \Doctrine\ORM\EntityRepository
{
}
