<?php

namespace xrpgBundle\Repository;

/**
 * pelopuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pelopuRepository extends \Doctrine\ORM\EntityRepository
{
}
