<?php

namespace xrpgBundle\Repository;

/**
 * peloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class peloRepository extends \Doctrine\ORM\EntityRepository
{
}
