<?php

namespace xrpgBundle\Repository;

/**
 * pielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pielRepository extends \Doctrine\ORM\EntityRepository
{
}
