<?php

namespace xrpgBundle\Repository;

/**
 * playsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class playsRepository extends \Doctrine\ORM\EntityRepository
{
}
