<?php

namespace xrpgBundle\Repository;

/**
 * posturasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class posturasRepository extends \Doctrine\ORM\EntityRepository
{
}
