<?php

namespace xrpgBundle\Repository;

/**
 * profesionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class profesionesRepository extends \Doctrine\ORM\EntityRepository
{
}
