<?php

namespace xrpgBundle\Repository;

/**
 * RelActionsTipoJuegoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelActionsTipoJuegoRepository extends \Doctrine\ORM\EntityRepository
{
}
