<?php

namespace xrpgBundle\Repository;

/**
 * RelActionsVirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelActionsVirRepository extends \Doctrine\ORM\EntityRepository
{
}
