<?php

namespace xrpgBundle\Repository;

/**
 * relactacttipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relactacttipoRepository extends \Doctrine\ORM\EntityRepository
{
}
