<?php

namespace xrpgBundle\Repository;

/**
 * relcharaccampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relcharaccampRepository extends \Doctrine\ORM\EntityRepository
{
}
