<?php

namespace xrpgBundle\Repository;

/**
 * RelCharacTipoJuegoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelCharacTipoJuegoRepository extends \Doctrine\ORM\EntityRepository
{
}
