<?php

namespace xrpgBundle\Repository;

/**
 * RelCharacAssetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelCharacAssetsRepository extends \Doctrine\ORM\EntityRepository
{
}
