<?php

namespace xrpgBundle\Repository;

/**
 * relcampcurrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relcampcurrRepository extends \Doctrine\ORM\EntityRepository
{
}
