<?php

namespace xrpgBundle\Repository;

/**
 * relcharacobjRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relcharacobjRepository extends \Doctrine\ORM\EntityRepository
{
}
