<?php

namespace xrpgBundle\Repository;

/**
 * RelCharacActionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelCharacActionsRepository extends \Doctrine\ORM\EntityRepository
{
}
