<?php

namespace xrpgBundle\Repository;

/**
 * RelCharacVirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelCharacVirRepository extends \Doctrine\ORM\EntityRepository
{
}
