<?php

namespace xrpgBundle\Repository;

/**
 * relcharaccurrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relcharaccurrRepository extends \Doctrine\ORM\EntityRepository
{
}
