<?php

namespace xrpgBundle\Repository;

/**
 * relmismanscampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relmismanscampRepository extends \Doctrine\ORM\EntityRepository
{
}
