<?php

namespace xrpgBundle\Repository;

/**
 * relmisacttipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relmisacttipoRepository extends \Doctrine\ORM\EntityRepository
{
}
