<?php

namespace xrpgBundle\Repository;

/**
 * relmisobjetoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relmisobjetoRepository extends \Doctrine\ORM\EntityRepository
{
}
