<?php

namespace xrpgBundle\Repository;

/**
 * relmanscampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relmanscampRepository extends \Doctrine\ORM\EntityRepository
{
}
