<?php

namespace xrpgBundle\Repository;

/**
 * relmanscaraccharRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relmanscaraccharRepository extends \Doctrine\ORM\EntityRepository
{
}
