<?php

namespace xrpgBundle\Repository;

/**
 * relmistipojuegoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relmistipojuegoRepository extends \Doctrine\ORM\EntityRepository
{
}
