<?php

namespace xrpgBundle\Repository;

/**
 * relmislugarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relmislugarRepository extends \Doctrine\ORM\EntityRepository
{
}
