<?php

namespace xrpgBundle\Repository;

/**
 * relmiscampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relmiscampRepository extends \Doctrine\ORM\EntityRepository
{
}
