<?php

namespace xrpgBundle\Repository;

/**
 * relmanprefcumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relmanprefcumRepository extends \Doctrine\ORM\EntityRepository
{
}
