<?php

namespace xrpgBundle\Repository;

/**
 * relmiscampprofRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relmiscampprofRepository extends \Doctrine\ORM\EntityRepository
{
}
