<?php

namespace xrpgBundle\Repository;

/**
 * relmanprefassetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relmanprefassetsRepository extends \Doctrine\ORM\EntityRepository
{
}
