<?php

namespace xrpgBundle\Repository;

/**
 * relmansmiscampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relmansmiscampRepository extends \Doctrine\ORM\EntityRepository
{
}
