<?php

namespace xrpgBundle\Repository;

/**
 * relplaysmansRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relplaysmansRepository extends \Doctrine\ORM\EntityRepository
{
}
