<?php

namespace xrpgBundle\Repository;

/**
 * relprofcampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relprofcampRepository extends \Doctrine\ORM\EntityRepository
{
}
