<?php

namespace xrpgBundle\Repository;

/**
 * relplayscharacRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relplayscharacRepository extends \Doctrine\ORM\EntityRepository
{
}
