<?php

namespace xrpgBundle\Repository;

/**
 * relplaysactionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relplaysactionsRepository extends \Doctrine\ORM\EntityRepository
{
}
