<?php

namespace xrpgBundle\Repository;

/**
 * relplayscumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relplayscumRepository extends \Doctrine\ORM\EntityRepository
{
}
