<?php

namespace xrpgBundle\Repository;

/**
 * ritmoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ritmoRepository extends \Doctrine\ORM\EntityRepository
{
}
