<?php

namespace xrpgBundle\Repository;

/**
 * tablacampoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tablacampoRepository extends \Doctrine\ORM\EntityRepository
{
}
