<?php

namespace xrpgBundle\Repository;

/**
 * tipoobjRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipoobjRepository extends \Doctrine\ORM\EntityRepository
{
}
