<?php

namespace xrpgBundle\Repository;

/**
 * TipoJuegoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoJuegoRepository extends \Doctrine\ORM\EntityRepository
{
}
