<?php

namespace xrpgBundle\Repository;

/**
 * tipocuerpoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipocuerpoRepository extends \Doctrine\ORM\EntityRepository
{
}
