<?php

namespace xrpgBundle\Repository;

/**
 * tipomisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipomisionRepository extends \Doctrine\ORM\EntityRepository
{
}
