<?php

namespace xrpgBundle\Repository;

/**
 * traseraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class traseraRepository extends \Doctrine\ORM\EntityRepository
{
}
