<?php

namespace xrpgBundle\Repository;

/**
 * virtudesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class virtudesRepository extends \Doctrine\ORM\EntityRepository
{
}
